name: Python Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Run hourly

jobs:
  python-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permission
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Run Python script
        run: python simple_test.py
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last run data"
          git push
